import { Sparkles, Shield } from "lucide-react";
import bsuAiLogo from "@assets/bsu-cai-logo.png";
import { useLocation } from "wouter";

export function PoweredByFooter() {
  const [location] = useLocation();
  const isCaiRoot = location === "/";

  if (isCaiRoot) {
    return null;
  }

  return (
    <footer className="mt-12 py-8 bg-gray-200 dark:bg-gray-800" data-testid="footer-powered-by">
      <div className="container mx-auto px-4 space-y-4">
        <div className="flex justify-center">
          <img
            src={bsuAiLogo}
            alt="BSU Center for Artificial Intelligence"
            className="h-12 dark:bg-white/90 dark:rounded-lg dark:px-3 dark:py-1"
            data-testid="img-bsu-ai-logo"
          />
        </div>
        <p className="text-center text-sm text-gray-900 dark:text-gray-300 flex items-center justify-center gap-2" style={{ textWrap: "balance" }} data-testid="text-powered-by">
          <Sparkles className="w-4 h-4 flex-shrink-0" />
          Powered by AI to help Bridgewater State University faculty create accessible, engaging course materials
        </p>
        <p className="text-center text-xs text-gray-700 dark:text-gray-400 flex items-center justify-center gap-2" style={{ textWrap: "balance" }} data-testid="text-privacy">
          <Shield className="w-3 h-3 flex-shrink-0" />
          Your course information and generated content are stored securely and are not shared with other users. Content generation uses Anthropic's Claude API — see{" "}
          <a href="https://www.anthropic.com/privacy" target="_blank" rel="noopener noreferrer" className="underline hover:opacity-80">Anthropic's privacy policy</a>{" "}
          for details on how API data is handled.
        </p>
        <p className="text-center text-xs text-gray-500 dark:text-gray-500 max-w-2xl mx-auto" style={{ textWrap: "balance" }} data-testid="text-bsu-disclaimer">
          Content generated by this tool is not stored or shared, and user data is not used to train AI models. AI-generated content may contain errors—please review all materials carefully. While every effort is made to support accessibility, Bridgewater State University does not guarantee full compliance or accuracy. Users are responsible for reviewing and verifying all content prior to use.
        </p>
      </div>
    </footer>
  );
}
